apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.serviceName }}
  labels:
    app: {{ .Values.zookeeper.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.zookeeper.name }}
  ports:
  - port: 2181
    name: client

